# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "hid" "xhci_hcd" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.rtlwifi_new config.boot.kernelPackages.wireguard ];
  # Deactivate discreet optimus/nvidia card
  boot.blacklistedKernelModules = [ "nouveau" ];

  fileSystems."/" =
    { device = "tank/encZFS/Nixos";
      fsType = "zfs";
    };

  fileSystems."/mnt/encZFS/Media" =
    { device = "tank/encZFS/Media";
      fsType = "zfs";
    };

  fileSystems."/mnt/encZFS/VMs" =
    { device = "tank/encZFS/VMs";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/81c7ba48-71dd-4060-8abe-5c5bcd5b4edc";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
